[CM-8222] re-factor api_experiment construction
comet-ml/comet-llm pull request #83
Opened 2023-10-06 16:52 UTC by jynx10

2023-10-06 17:35 UTC, jynx10 commented
@alexkuzmik I wasn't sure about 1 thing, if a property isnt initialized, do we want to return None?

2023-10-09 13:55 UTC, alexkuzmik requested changes

2023-10-09 13:55 UTC, alexkuzmik commented on src/comet_llm/experiment_api/experiment_api.py
> +    def initialize_parameters(self) -> None:
Let's name it `load_metadata()` so it will be clearer what it does (and rename the argument in from_existing_id method).

2023-10-09 13:55 UTC, alexkuzmik commented on src/comet_llm/experiment_api/experiment_api.py
> +        parsed_comet_url = config.comet_url().replace("/clientlib/", "")
Use `urllib` module to extract the root from URL. And better to move the building of the project url to a separate private helper function since it'll be used in `__init__` method as well.

2023-10-09 13:55 UTC, alexkuzmik commented on tests/unit/experiment_api/test_experiment_api.py
> +        assert tested.workspace == None
`is None`

2023-10-09 13:55 UTC, alexkuzmik commented on src/comet_llm/experiment_api/experiment_api.py
> +        self._project_name = project_name
Initialize `_project_url` with `None` here if workspace or project name is None, otherwise let's calculate it in the same way we do in `from_existing_id`

2023-10-09 13:55 UTC, alexkuzmik commented on src/comet_llm/experiment_api/experiment_api.py
> +        experiment_api._project_url = link[: link.rfind("/")]
To be consistent let's move project_url building to init method, not a big difference but allows us to have a unified logic.

2023-10-09 13:55 UTC, alexkuzmik commented on src/comet_llm/experiment_api/experiment_api.py
> +            workspace=workspace,
If the workspace or project is None, you can still find the names returned by the backend in response (the default ones).
In your code, None values will be passed to the init method. So get workspace and project from the response, and then pass them to `cls(...)`

2023-10-09 13:55 UTC, alexkuzmik commented on src/comet_llm/experiment_api/experiment_api.py
>      def project_url(self) -> str:
Make the property optional.

2023-10-10 20:02 UTC, alexkuzmik requested changes

2023-10-10 20:02 UTC, alexkuzmik commented on src/comet_llm/experiment_api/experiment_api.py
> +        cls, id: str, api_key: str, load_metadata: Optional[bool] = True
load_metadata is just bool

2023-10-11 08:01 UTC, alexkuzmik approved these changes

2023-10-11 08:01 UTC, merged